#!/usr/bin/env bash
#script that configures a new Ubuntu machine
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
