#!/usr/bin/env bash
#script that configures a new Ubuntu machine
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Hello World!" > /var/www/html/index.html
service nginx start
